### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by aforren1** [aforren1/online-color-habit#1]
- [x] Detect day via localStorage, or allow setting from URL params
- [x] Group assignment (via URL param)
- [x] Relax enter/exit time stuff (it's just distracting, so last 5 or so?)
- [x] pre-generate all possible groups (for finger-color-massed/spaced-switched combos) + prep times, for timed response
- [ ] ~Pausing mechanisms (if exit fullscreen/tab away, overlay button to continue & redo countdown on current trial)~ deferred
- [ ] Updated netlify lambda fns (with retry functionality)
- [ ] ~Info at beginning about browser consistency, preferred browsers~ will just send out note at beginning
- [x] If not prolific, assign random ID on day 1
- [x] debug mode to check timing on TR
- [x] Allow debugging of subtasks, so we don't have to go through whole shebang to check something?
